name: CI Pipeline

on:
    push:
        branches:
            - master
            - dev
            - 'feature/*'
    pull_request:
        branches:
            - master
            - dev
            - 'feature/*'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Set up JDK 24
                uses: actions/setup-java@v4
                with:
                    java-version: '24'
                    distribution: 'temurin'
                    cache: maven

            -   name: Build with Maven (skip tests)
                run: mvn clean install -DskipTests

            -   name: Upload build artifact
                uses: actions/upload-artifact@v4
                with:
                    name: platformone-jars
                    path: '**/target/*.jar'

    test:
        runs-on: ubuntu-latest
        needs: build

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Set up JDK 24
                uses: actions/setup-java@v4
                with:
                    java-version: '24'
                    distribution: 'temurin'
                    cache: maven

            -   name: Download build artifact
                uses: actions/download-artifact@v4
                with:
                    name: platformone-jars
                    path: target

            -   name: Start containers
                run: make docker-start

            -   name: Run tests
                run: mvn test

            -   name: Stop containers
                if: always()
                run: make docker-stop